### ISSUE TITLE
It is JS not in Python. ;-)

### ISSUE THREAD

**Issue by mdipierro** [alizain/ulid#1]
Great work. I ported it to Python. I hope the acknowledgement is sufficient.
https://github.com/mdipierro/ulid

**Comment by imdario** [comment]
I didn't want to create an issue but I ported it to Go https://github.com/imdario/go-ulid

**Comment by fvilers** [comment]
And I ported it to .Net https://github.com/fvilers/ulid.net

**Comment by mdipierro** [comment]
And ruby: https://github.com/rafaelsales/ulid

**Comment by Lewiscowles1986** [comment]
PHP port (I know, there's always one) :wink: 
https://github.com/Lewiscowles1986/ulid

**Comment by Lewiscowles1986** [comment]
Also now Java port: https://github.com/Lewiscowles1986/jULID

**Comment by ararslan** [comment]
Aaaaaaand now there's one in Julia: https://github.com/ararslan/ULID.jl

**Comment by alizain** [comment]
This is awesome guys! Thank you 👍

**Comment by mdipierro** [comment]
I have never see so much interest in a project this small. You are on to
something. It would be beneficial to have a single document with info that
you maintain, list links to implementations, and we reference back your
document, instead of including a copy of your readme file.

**Comment by alizain** [comment]
@mdipierro I appreciate your feedback. I've made the updates to the `README.md`
