### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by adius** [alizain/ulid#25]
It would be cool if you could add a cli so one can call `$ ulid` on the command line.

**Comment by jdanford** [comment]
The JS implementation is pretty minimal – what about opening this issue for a different implementation like [oklog/ulid](https://github.com/oklog/ulid)?

**Comment by adius** [comment]
I think the JS version is really easy to install via npm. That's why it's a good place for the cli.
My workaround at the moment is this script:

```js
#! /usr/bin/env node

const ulid = require('/Users/adrian/.config/yarn/global/node_modules/ulid')
const value = ulid()

process.stdout.write(value.toLowerCase())
```

**Comment by jdanford** [comment]
Good point, ease of installation is important! It wouldn't be hard for you to turn that script into a CLI, according to the [NPM docs](https://docs.npmjs.com/files/package.json#bin).

**Comment by adius** [comment]
I could do. Will it be merged @alizain ?

**Comment by alizain** [comment]
Yep, a CLI is totally fine, I'd be happy to accept a PR for it.
