### ISSUE TITLE
Add config to output lowercase

### ISSUE THREAD

**Issue by adius** [alizain/ulid#26]
I'm not a fan of all upper case. Would be cool to be able to change the default to all lower case.

**Comment by jdanford** [comment]
The issue I see is that [Crockford's base32](http://www.crockford.com/wrmg/base32.html) is intended to be written in uppercase, so a lowercase form of ULID (LULID?) would be better served by a different encoding such as [z-base-32](http://philzimmermann.com/docs/human-oriented-base-32-encoding.txt).

**Comment by adius** [comment]
> When decoding, upper and lower case letters are accepted

So an ulid decoder should support upper and lower case anyways ...

**Comment by jdanford** [comment]
You're right – it turns out ULID is already specified as case-insensitive. Are you proposing changing the default or just making it configurable? Your original comment contradicts the issue title.

**Comment by adius** [comment]
Sry for the unclear wording 😅. I just want it to be configurable. The default should probably remain upper case, as this also seems to be what crockford uses as default.

**Comment by alizain** [comment]
I'm open to outputting/formatting as lower-case, since the spec is case-insensitive. If you'd like to submit a PR, I'd be happy to accept it.

**Comment by adius** [comment]
Created a PR: https://github.com/alizain/ulid/pull/34

**Comment by alizain** [comment]
@adius, on reflection, I have decided that I will not be accepting this PR. The alternative is incredibly simple, and what we would use internally to make a ULID lowercase, so I would recommend for you to it instead:

```javascript
ulid().toLowerCase()
```
