### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by WorldMaker** [alizain/ulid#29]
Would you be interested in adding a Typescript definition file to your npm package? I'd be happy to contribute one via PR and help maintain it. There are other places to host such files, but it's always nicest when they exist right along the npm install.

(I ask first as an issue instead of sending a PR first as a courtesy, because I know not everyone wants to maintain Typescript definitions and "no" is a perfectly fine answer.)

**Comment by alizain** [comment]
Sure
