### ISSUE TITLE
Descending ULID

### ISSUE THREAD

**Issue by thdxr** [alizain/ulid#44]
I would like to create a ULID using a negative timestamp so when sorted in lexicographical order we get a descending sort.  However it seems, at least in the nodejs implementation, that an error is thrown if I specify a negative timestamp.

**Comment by alizain** [comment]
Would reversing the lexicographical sort (with positive timestamps) work for you? If not, then I don't exactly understand your problem. Before making changes to handle negative timestamps, I'd like to understand what you're trying to do.

**Comment by thdxr** [comment]
Reversing the  lexicographic sort does solve the problem. I basically needed a way to create "descending" ulids

**Comment by tuupola** [comment]
What is the problem you are trying to solve by using negative timestamps?

**Comment by alizain** [comment]
@thdxr, I'm assuming your problem has been solved, and closing this issue. Feel free to open it up again if things don't work for you!

**Comment by frikishaan** [comment]
@thdxr Were you able to solve the problem? Would you mind sharing the solution here?

**Comment by gkkachi** [comment]
Hi @frikishaan !
This is my solution: 

```javascript
const enc = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
function rev(ulid) { return [...ulid].map(x => enc[31 - enc.indexOf(x)]).join(''); }

// Test!
const ulid1 = '01ARZ3NDEKTSV4RRFFQ69G5FAV';
const ulid2 = '01ARYZ6S41TSV4RRFFQ69G5FAV';
console.log(ulid1 > ulid2);  // => true
console.log(rev(ulid1) < rev(ulid2));  // => true
```

**Comment by frikishaan** [comment]
Hi @gkkachi,
Thanks, have you tested it in production, is it collision free?

**Comment by gkkachi** [comment]
@frikishaan 

> have you tested it in production?

No.

> is it collision free?

Yes, the probability of collision for "descending ULIDs" is the same as that of the original ULIDs because `rev` function is bijective.
You can convert a "descending ULID" back to the original ULID by applying the `rev` function once more.
