### ISSUE TITLE
Use Typescript module support

### ISSUE THREAD

**Issue by WorldMaker** [alizain/ulid#51]
Since you are switching to Typescript, you can remove the manual code for the "UMD" wrapper and instead use ES2015 exports and let Typescript build your module wrappers for you with compile options in the `tsconfig.json`.

Also, you can remove `index.d.ts` if you already have an `index.ts` as Typescript will refer to that for its own definitions instead. (In fact the error I'm seeing with recent npm version is that the current `index.ts` is not a module and cannot be imported (because of the manual module wrapper confusing Typescript's type senses.)

I'd be happy to help with a PR if you would like, but this is the sort of thing might be better to do as learning experience, so I'll leave that up to you.

**Comment by alizain** [comment]
@WorldMaker thank you for your kind response. I was actually thinking about the same, and was going to look into it later this week, however since you're experiencing breakages, I will try to push a fix as soon as possible!

**Comment by alizain** [comment]
Phew! So I just pushed out the release with the fixes. The downside is that I had to remove global browser support. Any thoughts on non-hacky ways to support that functionality?

**Comment by WorldMaker** [comment]
My first thought is to just drop global browser support, it seems better these days to encourage fellow developers to use a module system, then to let them continue to avoid them in 2017.

That said, I've seen a few options. The obvious and it will feel like a hack is just to always set the global: `;(window || global || {} as any).ulid = factory(prng)`.

A growing pattern is to output only/primarily ES2015 modules, use [@std/esm](https://www.npmjs.com/package/@std/esm) to support the CommonJS-only versions of NodeJS, and use rollup (or babel or webpack, but for libraries it seems like rollup is the most common choice and easiest to configure to this particular library need) to build a dist JS file with a global export build from the ES2015 modules. (That just leaves AMD users out in the cold, which is possibly fine in 2017, but Typescript's `--outfile` support for a concatenated single file AMD dist JS file works pretty well there; you could have a default `tsconfig.json` for ES2015 modules and a secondary `tsconfig.amd.json` for AMD output.)

**Comment by alizain** [comment]
So I used parts of your advise. I'm using `tsc` to create the ES6+ compatible file, and the typings file. Then I use `rollup` to output ES+ compatible file which works with CommonJS, AMD, and the browser. Let me know if you have any trouble with it!

**Comment by WorldMaker** [comment]
Looks good to me. Thanks.
