### ISSUE TITLE
error when bundle for producation

### ISSUE THREAD

**Issue by ChiaJune** [alizain/ulid#54]
## ulid version
v2.2.1
## webpack version
v3.8.1
## library or framework
React v15.6.1

## error message
``` bash
ERROR in static/js/vendor.d444dbbb14fee2232a46.js from UglifyJs
Unexpected token: name (done) [./node_modules/ulid/lib/index.js:20,0][static/js/vendor.d444dbbb14fee2232a46.js:92761,8]
```

**Comment by alizain** [comment]
@ChiaJune, I'm guessing that a transpiler solved your issues. Feel free re-open if you have any other questions.
