### ISSUE TITLE
Rust language version

### ISSUE THREAD

**Issue by mmacedoeu** [alizain/ulid#8]
Made a rust-lang.org version

https://github.com/mmacedoeu/rulid.rs

**Comment by alizain** [comment]
Thank you! @mmacedoeu have you implemented the binary format?

**Comment by mmacedoeu** [comment]
Not atm

**Comment by mmacedoeu** [comment]
rulid now features binary as byte array and numeric as a composite u64 integer tuple, so If you want high performance indexing based on ulid you can store on databases as a composite key

**Comment by alizain** [comment]
Closing this issue, sorry for the delayed response. I've also updated the docs to mention the binary implementation!
